.PHONY: deb deb-clean deb-and-clean local-install local-uninstall

PACKAGE_NAME=tailscale-appindicator

deb:
	dpkg-buildpackage -us -uc
	mv ../$(PACKAGE_NAME)_*.deb .

deb-clean:
	dpkg-buildpackage -T clean

local-install:
	/usr/bin/bash scripts/install.sh

local-uninstall:
	/usr/bin/bash scripts/uninstall.sh

deb-and-clean: deb deb-clean
